apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-app-edge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dhinesh-0309/Edge_cloud_computing_project-.git
    targetRevision: HEAD
    path: Documents/capstone-project/Edge  # <-- Points to the edge directory
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
