apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: edge-control-plane # Or your correct edge node name
      containers:
      - name: capstone-app-container
        image: dhineshpandian/capstone-app:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080