apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      
      containers:
      - name: capstone-app-container
        image: dhineshpandian/capstone-app:v2
        ports:
        - containerPort: 8080

